version: 0.0
os: linux
files:
  - source: /
    destination: /local/web/www
hooks:
  BeforeInstall:
    - location: sbin/preinstall.sh
      runas: root
  AfterInstall:
    - location: sbin/sitesetup.pl
      timeout: 300
      runas: root
  ApplicationStart:
    - localtion: sbin/start_server.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: sbin/stop_server.sh
      timeout: 300
      runas: root